// const oracledb = require("oracledb");
const config = require("../../config/dbConfig");

async function amend_account_relation(req, res) {
  try {
    // Get a connection to the Oracle database
    const connection = await oracledb.getConnection(config);

    const {
      relation_no,
      customer_number,
      first_name,
      surname,
      last_name,
      other_name,
      gender,
      suffix,
      title,
      date_of_birth,
      place_of_birth,
      nationality,
      religion,
      region,
      district,
      domicile_country,
      residence_country,
      residence_status,
      resident_since,
      number_of_yrs_of_residence,
      marital_status,
      number_of_children,
      number_of_dependants,
      mothers_maiden_name,
      next_of_kin,
      next_of_kin_address,
      next_of_kin_phone,
      id_type,
      id_number,
      id_issue_date,
      id_expiry_date,
      id_issued_authority,
      id_issued_at,
      residential_address,
      residency_type,
      postal_address,
      mobile1,
      mobile2,
      line_phone,
      email_address,
      staff_category,
      nature_of_work,
      place_of_work,
      work_place_physical_address,
      work_place_postal_address,
      work_place_phone_number,
      qualification,
      profession,
      monthly_income,
      number_of_cars,
      preferred_atm_lang,
      preferred_phone_lang,
      branch_code,
      posted_by,
      posting_date,
      posting_sys_date,
      posting_terminal,
      last_upd_by,
      last_upd_posting_date,
      last_upd_posting_sys_date,
      last_upd_posting_terminal,
      app_flag,
      approval_by,
      approval_posting_date,
      approval_posting_sys_date,
      approval_posting_terminal,
      upd_approval_by,
      upd_approval_posting_date,
      upd_approval_posting_sys_date,
      upd_approval_posting_terminal,
      constitutional_code,
      relationship_type,
      registration_no,
      tin,
      premises_owner,
      number_of_employees,
      ind_customer_base,
      corp_customer_base,
      nature_of_business,
      upd_flag,
      preferred_lang,
      cosolidated_statement,
      statement_language,
      cooperate_customer,
      risk_code,
      posting_sys_time,
      template_id,
      reason_code,
      reason_comment,
      amended_by,
      amended_sys_date,
      amended_sys_time,
      amended_date,
      amended_ip,
      amended_terminal,
      app_status,
      posting_ip,
      app_ip,
      approval_sys_time,
      approval_ip,
      rc_code,
      rc_reason,
      amended_status,
      alias_name,
      mothers_fname,
      mothers_ma_name,
      mothers_mi_name,
      rel_flag,
      building_name,
      location,
      city,
      street_name,
      other_id_nos,
      approver_state,
      relation_cat,
      pre_rel_flag,
      contact_method,
      contact_start_time,
      contact_end_time,
      preferred_day_mon,
      preferred_day_tue,
      preferred_day_wed,
      preferred_day_thu,
      preferred_day_fri,
      preferred_day_sat,
      preferred_day_sun,
      opt_out,
      donot_call,
      donot_mail,
      donot_email,
      donot_share,
      trustee_flag,
      approver_lim,
      approver_lim_ib,
      zip_code,
      kyc_flag,
      nin,
      nin_expiry_date,
      col_aud_val,
      flag_CAA,
    } = req.body;
    console.log(req.body);

    // Call the stored procedure
    const result = await connection.execute(
      `BEGIN PKG_STATICAMEND_RT.PRC_RELATION_SAVE_RT(
      :p_relation_no, :p_customer_number, :p_first_name,:p_surname,:p_last_name,:p_other_name,:p_gender,:p_suffix,:p_title,:p_date_of_birth,
      :p_place_of_birth, :p_nationality, :p_religion,:p_region,:p_district,:p_domicile_country,:p_residence_country,:p_residence_status,:p_resident_since,:p_number_of_yrs_of_residence,
      :p_marital_status, :p_number_of_children, :p_number_of_dependants,:p_mothers_maiden_name,:p_next_of_kin,:p_next_of_kin_address,:p_next_of_kin_phone,:p_id_type,:p_id_number,:p_id_issue_date,
      :p_id_expiry_date, :p_id_issued_authority, :p_id_issued_at,:p_residential_address,:p_residency_type,:p_postal_address,:p_mobile1,:p_mobile2,:p_line_phone,:p_email_address,
      :p_staff_category, :p_nature_of_work, :p_place_of_work,:p_work_place_physical_address,:p_work_place_postal_address,:p_work_place_phone_number,:p_qualification,:p_profession,:p_monthly_income,:p_number_of_cars,
      :p_preferred_atm_lang, :p_preferred_phone_lang, :p_branch_code,:p_posted_by,:p_posting_date,:p_posting_sys_date,:p_posting_terminal,:p_last_upd_by,:p_last_upd_posting_date,:p_last_upd_posting_sys_date,
      :p_last_upd_posting_terminal, :p_app_flag, :p_approval_by,:p_approval_posting_date,:p_approval_posting_sys_date,:p_approval_posting_terminal,:p_upd_approval_by,:p_upd_approval_posting_date,:p_upd_approval_posting_sys_date,:p_upd_approval_posting_terminal,
      :p_constitutional_code, :p_relationship_type, :p_registration_no,:p_tin,:p_premises_owner,:p_number_of_employees,:p_ind_customer_base,:p_corp_customer_base,:p_nature_of_business,:p_upd_flag,
      :p_preferred_lang, :p_cosolidated_statement, :p_statement_language,:p_cooperate_customer,:p_risk_code,:p_posting_sys_time,:p_template_id,:p_reason_code,:p_reason_comment,:p_amended_by,
      :p_amended_sys_date, :p_amended_sys_time, :p_amended_date,:p_amended_ip,:p_amended_terminal,:p_app_status,:p_posting_ip,:p_app_ip,:p_approval_sys_time,:p_approval_ip,
      :p_rc_code, :p_rc_reason, :p_amended_status,:p_alias_name,:p_mothers_fname,:p_mothers_ma_name,:p_mothers_mi_name,:p_rel_flag,:p_building_name,:p_location,
      :p_city, :p_street_name, :p_other_id_nos,:p_approver_state,:p_relation_cat,:p_pre_rel_flag,:p_contact_method,:p_contact_start_time,:p_contact_end_time,:p_preferred_day_mon,:p_preferred_day_tue,
      :p_preferred_day_wed, :p_preferred_day_thu, :p_preferred_day_fri,:p_preferred_day_sat,:p_preferred_day_sun,:p_opt_out,:p_donot_call,:p_donot_mail,:p_donot_email,:p_donot_share,
      :p_trustee_flag, :p_approver_lim, :p_approver_lim_ib,:p_zip_code,:p_kyc_flag,:p_nin,:p_nin_expiry_date,:p_col_aud_val,:P_flag_CAA,:p_result
      ); END;`,
      {
        p_relation_no: { dir: oracledb.BIND_IN, val: relation_no },
        p_customer_number: { dir: oracledb.BIND_IN, val: customer_number },
        p_first_name: { dir: oracledb.BIND_IN, val: first_name },
        p_surname: { dir: oracledb.BIND_IN, val: surname },
        p_last_name: { dir: oracledb.BIND_IN, val: last_name },
        p_other_name: { dir: oracledb.BIND_IN, val: other_name },
        p_gender: { dir: oracledb.BIND_IN, val: gender },
        p_suffix: { dir: oracledb.BIND_IN, val: suffix },
        p_title: { dir: oracledb.BIND_IN, val: title },
        p_date_of_birth: { dir: oracledb.BIND_IN, val: date_of_birth },
        p_place_of_birth: { dir: oracledb.BIND_IN, val: place_of_birth },
        p_nationality: { dir: oracledb.BIND_IN, val: nationality },
        p_religion: { dir: oracledb.BIND_IN, val: religion },
        p_region: { dir: oracledb.BIND_IN, val: region },
        p_district: { dir: oracledb.BIND_IN, val: district },
        p_domicile_country: { dir: oracledb.BIND_IN, val: domicile_country },
        p_residence_country: { dir: oracledb.BIND_IN, val: residence_country },
        p_residence_status: { dir: oracledb.BIND_IN, val: residence_status },
        p_resident_since: { dir: oracledb.BIND_IN, val: resident_since },
        p_number_of_yrs_of_residence: {
          dir: oracledb.BIND_IN,
          val: number_of_yrs_of_residence,
        },
        p_marital_status: { dir: oracledb.BIND_IN, val: marital_status },
        p_number_of_children: {
          dir: oracledb.BIND_IN,
          val: number_of_children,
        },
        p_number_of_dependants: {
          dir: oracledb.BIND_IN,
          val: number_of_dependants,
        },
        p_mothers_maiden_name: {
          dir: oracledb.BIND_IN,
          val: mothers_maiden_name,
        },
        p_next_of_kin: { dir: oracledb.BIND_IN, val: next_of_kin },
        p_next_of_kin_address: {
          dir: oracledb.BIND_IN,
          val: next_of_kin_address,
        },
        p_next_of_kin_phone: { dir: oracledb.BIND_IN, val: next_of_kin_phone },
        p_id_type: { dir: oracledb.BIND_IN, val: id_type },
        p_id_number: { dir: oracledb.BIND_IN, val: id_number },
        p_id_issue_date: { dir: oracledb.BIND_IN, val: id_issue_date },
        p_id_expiry_date: { dir: oracledb.BIND_IN, val: id_expiry_date },
        p_id_issued_authority: {
          dir: oracledb.BIND_IN,
          val: id_issued_authority,
        },
        p_id_issued_at: { dir: oracledb.BIND_IN, val: id_issued_at },
        p_residential_address: {
          dir: oracledb.BIND_IN,
          val: residential_address,
        },
        p_residency_type: { dir: oracledb.BIND_IN, val: residency_type },
        p_postal_address: { dir: oracledb.BIND_IN, val: postal_address },
        p_mobile1: { dir: oracledb.BIND_IN, val: mobile1 },
        p_mobile2: { dir: oracledb.BIND_IN, val: mobile2 },
        p_line_phone: { dir: oracledb.BIND_IN, val: line_phone },
        p_email_address: { dir: oracledb.BIND_IN, val: email_address },
        p_staff_category: { dir: oracledb.BIND_IN, val: staff_category },
        p_nature_of_work: { dir: oracledb.BIND_IN, val: nature_of_work },
        p_place_of_work: { dir: oracledb.BIND_IN, val: place_of_work },
        p_work_place_physical_address: {
          dir: oracledb.BIND_IN,
          val: work_place_physical_address,
        },
        p_work_place_postal_address: {
          dir: oracledb.BIND_IN,
          val: work_place_postal_address,
        },
        p_work_place_phone_number: {
          dir: oracledb.BIND_IN,
          val: work_place_phone_number,
        },
        p_qualification: { dir: oracledb.BIND_IN, val: qualification },
        p_profession: { dir: oracledb.BIND_IN, val: profession },
        p_monthly_income: { dir: oracledb.BIND_IN, val: monthly_income },
        p_number_of_cars: { dir: oracledb.BIND_IN, val: number_of_cars },
        p_preferred_atm_lang: {
          dir: oracledb.BIND_IN,
          val: preferred_atm_lang,
        },
        p_preferred_phone_lang: {
          dir: oracledb.BIND_IN,
          val: preferred_phone_lang,
        },
        p_branch_code: { dir: oracledb.BIND_IN, val: branch_code },
        p_posted_by: { dir: oracledb.BIND_IN, val: posted_by },
        p_posting_date: { dir: oracledb.BIND_IN, val: posting_date },
        p_posting_sys_date: { dir: oracledb.BIND_IN, val: posting_sys_date },
        p_posting_terminal: { dir: oracledb.BIND_IN, val: posting_terminal },
        p_last_upd_by: { dir: oracledb.BIND_IN, val: last_upd_by },
        p_last_upd_posting_date: {
          dir: oracledb.BIND_IN,
          val: last_upd_posting_date,
        },
        p_last_upd_posting_sys_date: {
          dir: oracledb.BIND_IN,
          val: last_upd_posting_sys_date,
        },
        p_last_upd_posting_terminal: {
          dir: oracledb.BIND_IN,
          val: last_upd_posting_terminal,
        },
        p_app_flag: { dir: oracledb.BIND_IN, val: app_flag },
        p_approval_by: { dir: oracledb.BIND_IN, val: approval_by },
        p_approval_posting_date: {
          dir: oracledb.BIND_IN,
          val: approval_posting_date,
        },
        p_approval_posting_sys_date: {
          dir: oracledb.BIND_IN,
          val: approval_posting_sys_date,
        },
        p_approval_posting_terminal: {
          dir: oracledb.BIND_IN,
          val: approval_posting_terminal,
        },
        p_upd_approval_by: { dir: oracledb.BIND_IN, val: upd_approval_by },
        p_upd_approval_posting_date: {
          dir: oracledb.BIND_IN,
          val: upd_approval_posting_date,
        },
        p_upd_approval_posting_sys_date: {
          dir: oracledb.BIND_IN,
          val: upd_approval_posting_sys_date,
        },
        p_upd_approval_posting_terminal: {
          dir: oracledb.BIND_IN,
          val: upd_approval_posting_terminal,
        },
        p_constitutional_code: {
          dir: oracledb.BIND_IN,
          val: constitutional_code,
        },
        p_relationship_type: { dir: oracledb.BIND_IN, val: relationship_type },
        p_registration_no: { dir: oracledb.BIND_IN, val: registration_no },
        p_tin: { dir: oracledb.BIND_IN, val: tin },
        p_premises_owner: { dir: oracledb.BIND_IN, val: premises_owner },
        p_number_of_employees: {
          dir: oracledb.BIND_IN,
          val: number_of_employees,
        },
        p_ind_customer_base: { dir: oracledb.BIND_IN, val: ind_customer_base },
        p_corp_customer_base: {
          dir: oracledb.BIND_IN,
          val: corp_customer_base,
        },
        p_nature_of_business: {
          dir: oracledb.BIND_IN,
          val: nature_of_business,
        },
        p_upd_flag: { dir: oracledb.BIND_IN, val: upd_flag },
        p_preferred_lang: { dir: oracledb.BIND_IN, val: preferred_lang },
        p_cosolidated_statement: {
          dir: oracledb.BIND_IN,
          val: cosolidated_statement,
        },
        p_statement_language: {
          dir: oracledb.BIND_IN,
          val: statement_language,
        },
        p_cooperate_customer: {
          dir: oracledb.BIND_IN,
          val: cooperate_customer,
        },
        p_risk_code: { dir: oracledb.BIND_IN, val: risk_code },
        p_posting_sys_time: { dir: oracledb.BIND_IN, val: posting_sys_time },
        p_template_id: { dir: oracledb.BIND_IN, val: template_id },
        p_reason_code: { dir: oracledb.BIND_IN, val: reason_code },
        p_reason_comment: { dir: oracledb.BIND_IN, val: reason_comment },
        p_amended_by: { dir: oracledb.BIND_IN, val: amended_by },
        p_amended_sys_date: { dir: oracledb.BIND_IN, val: amended_sys_date },
        p_amended_sys_time: { dir: oracledb.BIND_IN, val: amended_sys_time },
        p_amended_date: { dir: oracledb.BIND_IN, val: amended_date },
        p_amended_ip: { dir: oracledb.BIND_IN, val: amended_ip },
        p_amended_terminal: { dir: oracledb.BIND_IN, val: amended_terminal },
        p_app_status: { dir: oracledb.BIND_IN, val: app_status },
        p_posting_ip: { dir: oracledb.BIND_IN, val: posting_ip },
        p_app_ip: { dir: oracledb.BIND_IN, val: app_ip },
        p_approval_sys_time: { dir: oracledb.BIND_IN, val: approval_sys_time },
        p_approval_ip: { dir: oracledb.BIND_IN, val: approval_ip },
        p_rc_code: { dir: oracledb.BIND_IN, val: rc_code },
        p_rc_reason: { dir: oracledb.BIND_IN, val: rc_reason },
        p_amended_status: { dir: oracledb.BIND_IN, val: amended_status },
        p_alias_name: { dir: oracledb.BIND_IN, val: alias_name },
        p_mothers_fname: { dir: oracledb.BIND_IN, val: mothers_fname },
        p_mothers_ma_name: { dir: oracledb.BIND_IN, val: mothers_ma_name },
        p_mothers_mi_name: { dir: oracledb.BIND_IN, val: mothers_mi_name },
        p_rel_flag: { dir: oracledb.BIND_IN, val: rel_flag },
        p_building_name: { dir: oracledb.BIND_IN, val: building_name },
        p_location: { dir: oracledb.BIND_IN, val: location },
        p_city: { dir: oracledb.BIND_IN, val: city },
        p_street_name: { dir: oracledb.BIND_IN, val: street_name },
        p_other_id_nos: { dir: oracledb.BIND_IN, val: other_id_nos },
        p_approver_state: { dir: oracledb.BIND_IN, val: approver_state },
        p_relation_cat: { dir: oracledb.BIND_IN, val: relation_cat },
        p_pre_rel_flag: { dir: oracledb.BIND_IN, val: pre_rel_flag },
        p_contact_method: { dir: oracledb.BIND_IN, val: contact_method },
        p_contact_start_time: {
          dir: oracledb.BIND_IN,
          val: contact_end_time,
        },
        p_contact_end_time: {
          dir: oracledb.BIND_IN,
          val: contact_start_time,
        },
        p_preferred_day_mon: { dir: oracledb.BIND_IN, val: preferred_day_mon },
        p_preferred_day_tue: { dir: oracledb.BIND_IN, val: preferred_day_tue },
        p_preferred_day_wed: { dir: oracledb.BIND_IN, val: preferred_day_wed },
        p_preferred_day_thu: { dir: oracledb.BIND_IN, val: preferred_day_thu },
        p_preferred_day_fri: { dir: oracledb.BIND_IN, val: preferred_day_fri },
        p_preferred_day_sat: { dir: oracledb.BIND_IN, val: preferred_day_sat },
        p_preferred_day_sun: { dir: oracledb.BIND_IN, val: preferred_day_sun },
        p_opt_out: { dir: oracledb.BIND_IN, val: opt_out },
        p_donot_call: { dir: oracledb.BIND_IN, val: donot_call },
        p_donot_mail: { dir: oracledb.BIND_IN, val: donot_mail },
        p_donot_email: { dir: oracledb.BIND_IN, val: donot_email },
        p_donot_share: { dir: oracledb.BIND_IN, val: donot_share },
        p_trustee_flag: { dir: oracledb.BIND_IN, val: trustee_flag },
        p_approver_lim: { dir: oracledb.BIND_IN, val: approver_lim },
        p_approver_lim_ib: { dir: oracledb.BIND_IN, val: approver_lim_ib },
        p_zip_code: { dir: oracledb.BIND_IN, val: zip_code },
        p_kyc_flag: { dir: oracledb.BIND_IN, val: kyc_flag },
        p_nin: { dir: oracledb.BIND_IN, val: nin },
        p_nin_expiry_date: { dir: oracledb.BIND_IN, val: nin_expiry_date },
        p_col_aud_val: { dir: oracledb.BIND_IN, val: col_aud_val },
        P_flag_CAA: { dir: oracledb.BIND_IN, val: flag_CAA },
        p_result: { dir: oracledb.BIND_OUT },
      }
    );

    // Commit the transaction
    // await connection.commit();

    // Release the connection
    // await connection.close();

    let response = result.outBinds.p_result;
    console.log(response);
    if (
      result.outBinds.p_result ===
      "Relation does not exist in TB_RELATION or TB_RELATION_TEMP."
    ) {
      res.send({
        success: "N",
        message: "Relation does not exist, kindly check.",
      });
      //   res.send({ success: "N", message: response });
    } else {
      res.status(200).json({ success: "Y", message: response });
      //   res
      //     .status(200)
      //     .json({ success: "Y", message: "Relation saved successfully" });
    }
  } catch (error) {
    console.error("Error executing procedure:", error);
    res.status(500).json({ error: "Internal server error." });
  }
}

module.exports = {
  amend_account_relation,
};
